<?php

/**
 * @file
 * A module to integrate Drupal with Google Drive.
 * Created by:  James Barnett, Babson College 2014.
 */

/**
 * Implements hook_menu().
 */
function gcalendar_menu() {
  $items = array();

  $items['gcalendar'] = array(
    'title' => 'gcalendar',
    'type' => MENU_CALLBACK,
    'page callback' => 'gcalendar_callback',
    'access callback' => TRUE,
  );

  $items['admin/config/gcalendar'] = array(
    'title' => 'GCalendar Settings',
    'description' => 'Configuration of who can upload to google docs from an OG gcalendar block',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gcalendar_settings_form'),
    'access arguments' => array('administer gcalendar'),
    'file' => 'gcalendar.admin.inc',
  );

  $items['gcalendar_get_google_token'] = array(
    'title' => 'Gcalendar Get Google Token',
    'page callback' => 'gcalendar_get_google_token_page',
    'access callback' => TRUE,
    'file' => 'gcalendar.admin.inc',
  );

  $items['gcalendar_set_up_watch_channel'] = array(
    'title' => 'Gcalendar Set up Watch Channel',
    'page callback' => 'gcalendar_set_up_watch_channel',
    'access callback' => TRUE,
    'file' => 'gcalendar.admin.inc',
  );
  
  return $items;
}

function gcalendar_callback() {
  global $user;
  
  // TODO get user form channel id
  watchdog('calendar', var_export($_SERVER, TRUE));

  if (!isset($_SERVER['X-Goog-Channel-ID'])) {
    exit();
  }
  $channel_id = $_SERVER['X-Goog-Channel-ID'];

  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'user')
    ->entityCondition('bundle', 'article')
    ->fieldCondition('field_gcalendar_watch_channel_id', 'value', $channel_id, '=')
    ->range(0, 1);

  $result = $query->execute();

  if (isset($result['node'])) {
    $uids = array_keys($result['user']);
    $users = entity_load('user', $uids);
    $user = reset($users);
  }

  $client = _gcalendar_get_google_client();
  
  $update = array();

  if (isset($user->data['calendar_sync_token'])) {
    $syncToken = $user->data['calendar_sync_token'];
    $user->data['calendar_sync_token'] = gcalendar_sync($client, $update, null, $syncToken);
  }
  else {
    // no need to have a full sync here
  }

  // TODO call wechat to send the updates

  http_response_code(200);

  drupal_exit();
}

/**
 * Get the refresh token.
 *
 * The refresh token most be requested to google, which involves redriecting to
 * google for it so the user can confirm the permissions being asked for.
 *
 * @param $state
 *   Additional state information that will be returned to final page.
 */
function gcalendar_get_google_token($state = array()) {
  global $user;
  
  $url = "https://accounts.google.com/o/oauth2/auth";
  $connection_info = gcalendar_get_connection_settings();
  $client_id = $connection_info['client_id'];
  $client_secret = $connection_info['client_secret'];
  $redirect_uri = "http://" . $_SERVER['HTTP_HOST'] . "/gcalendar_get_google_token";
  $approval_prompt = "force";
  $grant_type = "authorization_code";
  $scope = "https://www.googleapis.com/auth/calendar";


  $params_request = array(
    "response_type" => "code",
    "client_id" => "$client_id",
    "redirect_uri" => "$redirect_uri",
    "approval_prompt" => "$approval_prompt",
    "scope" => "$scope",
    'state' => $state,
  );
  // To make sure the request is valid, as suggested by google documentation.
  $params_request['state']['token'] = drupal_get_token($client_secret);
  $params_request['state'] = serialize($params_request['state']);

  $request_to = $url . '?' . http_build_query($params_request);

  if (isset($_GET['code'])) {
    // try to get an access token
    $code = $_GET['code'];
    $url = 'https://accounts.google.com/o/oauth2/token';
    $params = array(
      "code" => $code,
      "client_id" => "$client_id",
      "client_secret" => "$client_secret",
      "redirect_uri" => "$redirect_uri",
      "grant_type" => "$grant_type"
    );

    $curl = curl_init($url);
    curl_setopt($curl, CURLOPT_POST, TRUE);
    curl_setopt($curl, CURLOPT_POSTFIELDS, $params);
    curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, FALSE);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);

    $json_response = curl_exec($curl);
    curl_close($curl);

    $auth_obj = json_decode($json_response);
    $user->data['gcalender_access_token'] = $auth_obj->access_token;
    $user->data['gcalender_refresh_token'] = $auth_obj->refresh_token;
    
    user_save($user);

    watchdog('gcalendar', 'access token: @token', array('@token' => $auth_obj->access_token), WATCHDOG_DEBUG);
    watchdog('gcalendar', 'refresh token: @token', array('@token' => $auth_obj->refresh_token), WATCHDOG_DEBUG);
    
    $result = array();
    $result['refresh_token'] = $auth_obj->refresh_token;
    $result['access_token'] = $auth_obj->access_token;
    return $result;
  }
  else {
    return array('redirect' => $request_to);
  }
  
  // TODO redirect back
}

/**
 * Get the client ID, password, and refresh token.
 *
 * @param $use_og
 *   Check OG group.
 * @param @group_context
 *   Instead of using current group context, use this.
 */
function gcalendar_get_connection_settings($use_og = TRUE, $group_context = NULL) {
  $return = array();
  $return['client_id'] = variable_get('gcalendar_clientid', '');
  $return['client_secret'] = variable_get('gcalendar_secret', '');
  $return['refresh_token'] = variable_get('gcalendar_refresh_token', '');
  return $return;
}

/**
 * TODO Create notification channel 
 * 
 * @return array
 */

/*
 *  Function connects to google drive.
 */
function gcalendar_set_up_watch_channel() {
  global $user;
  try {
    $client = _gcalendar_get_google_client();
    $service = new Google_Service_Calendar($client);
    
    $channel_id = uuid_generate();
    $channel = new Google_Service_Calendar_Channel();
    $channel->setId($channel_id);
    $channel->setType('web_hook');
    $channel->setAddress("https://" . $_SERVER['HTTP_HOST'] . "/gcalendar");
    
    $return = $service->events->watch('primary', $channel);
    
    if ($channel_id  = $return->getId()) {
      $user->field_gcalendar_watch_channel_id[0][LANGUAGE_NONE]['value'] = $channel_id;
    }
  }
  catch (Exception $e) {
    watchdog('gcalendar', 'Unable to connect to google, error: @error', array('@error' => $e->getMessage()), WATCHDOG_ERROR);
    if (user_access('administer gcalendar')) {
      drupal_set_message(t('Unable to connect to google drive, error @error.', array('@error' => $e->getMessage())), 'error');
    }
    else {
      drupal_set_message(t('Unable to connect to google drive, please contact an administrator'), 'error');
    }
    return FALSE;
  }
}

function _gcalendar_get_google_client($redirect_uri = NULL, $client_id = NULL, $client_secret = NULL, $refresh_token = NULL) {
  global $user;
  
  if ($path = libraries_get_path('google-api-php-client')) {
    require_once $path.'/vendor/autoload.php';
  }
  else {
    watchdog('gcalendar', 'Unable to find google api library, see gcalendar README for instructions.', array(), WATCHDOG_ERROR);
    if (user_access('administer gcalendar')) {
      drupal_set_message(t('Unable to find google drive library, see README.txt for installation instructions.'), 'error');
    }
    else {
      drupal_set_message(t('Unable to connect to google drive, please contact an administrator'), 'error');
    }
    return FALSE;
  }

  $connection_info = gcalendar_get_connection_settings();
  try {
    $client = new Google_Client();
    $client->setClientId($client_id ? $client_id : $connection_info['client_id']);
    $client->setClientSecret($client_secret ? $client_secret : $connection_info['client_secret']);
    $client->setRedirectUri('http://' . $_SERVER['HTTP_HOST'] . '/gcalendar' . $redirect_uri);
    $client->addScope("https://www.googleapis.com/auth/calender");
    
    if (isset($user->data['gcalender_access_token'])) {
      $client->setAccessToken($user->data['gcalender_access_token']);
      if ($client->isAccessTokenExpired()) {
        //todo
      }
    }
    else {
      // todo
      return false;
    }
    
    return $client;
  }
  catch (Exception $e) {
      watchdog('gcalendar', 'Unable to connect to google, error: @error', array('@error' => $e->getMessage()), WATCHDOG_ERROR);
      if (user_access('administer gcalendar')) {
        drupal_set_message(t('Unable to connect to google drive, error @error.', array('@error' => $e->getMessage())), 'error');
      }
      else {
        drupal_set_message(t('Unable to connect to google drive, please contact an administrator'), 'error');
      }
      return FALSE;
    }
}

/**
 * Implements hook_action_info().
 */
function gcalendar_sync(Google_Service_Calendar $service, &$updated=array(), $pageToken=null, $nextSyncToken=null) {
  $optParams = array();
  if ($pageToken) {
    $optParams['pageToken'] = $pageToken;
  }
  if ($nextSyncToken) {
    $optParams['nextSyncToken'] = $nextSyncToken;
  }
  
  $events = $service->events->listEvents('primary', $optParams);
  
  while(!$nextSyncToken = $events->getNextSyncToken()) {
    foreach ($events->getItems() as $event) {
      if ($nextSyncToken) {
        $updated[] = $event->getSummary();
      }
      else {
        // full sync here
        // skip
      }
    }

    $pageToken = $events->getNextPageToken();

    return gcalendar_sync($service, $pageToken, $nextSyncToken);
  }
  
  return $nextSyncToken;
}

